version: "3.7"
services:
    loremipsum:
        container_name: loremipsum
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "5000:5000"
