version: "3"
services:
    example:
        container_name: unlucky_strike
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "127.0.0.1:25002:2001"
