version: "3"
services:
  rooted:
    container_name: rooted
    build:
        dockerfile: ./deploy/Dockerfile
        context: ../
    logging:
        driver: "json-file"
    ports:
        - "2007:1337"
    #TODO: remove
    stdin_open: true
    tty: true
